import Bio from "@/components/bio/bio";
import Projects from "@/components/projects/projects";
import Socials from "@/components/socials/socials";
import Article from "@/components/layout/article/article";
import Head from "next/head";

export default function Home() {
    return (
        <>
            <Head>
                <title>Ilia Karavaev - Homepage</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com"/>


            </Head>
            <Article title={'Homepage'}>
                <Bio/>
                <Projects/>
                <Socials/>
            </Article>

        </>
    )
}
