import Head from 'next/head'
import {Box} from "@chakra-ui/react";
import Bio from "@/components/bio";
import Projects from "@/components/projects";
import Socials from "@/components/socials";
import Navbar from "@/components/navbar/navbar";

export default function Home() {
    return (
        <>
            <Head>
                <title>Ilia Karavaev - Homepage</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com"/>
                <link
                    href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@300;400;500;700;800&display=swap"
                    rel="stylesheet"/>


            </Head>
            <Box as={'main'} backgroundColor={'#202023'}>
                <Box
                    color={'white'}
                    overflow={'hidden'}
                    margin={'0 auto'}
                >

                    <Navbar/>
                    <Bio/>
                    <Projects/>
                    <Socials/>
                </Box>
            </Box>
        </>
    )
}
