import * as S from './page.styled';
import Navbar from "@/components/navbar/navbar";
import Head from "next/head";

interface PageProps {
    children: string | JSX.Element | JSX.Element[],
}

export default function ({children}: PageProps) {
    return (
        <>
            <Head>
                <title>Ilia Karavaev - Homepage</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com"/>
                <link
                    href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@300;400;500;700;800&display=swap"
                    rel="stylesheet"/>


            </Head>
            <S.Main>
                <Navbar/>
                {children}
            </S.Main>

        </>
    )
}