import * as S from './page.styled';
import Navbar from "@/components/navbar/navbar";
import Head from "next/head";
import {Memoized3dObject} from "@/components/model/model";

interface PageProps {
    children: string | JSX.Element | JSX.Element[],
}

export default function Page({children}: PageProps) {
    return (
        <>
            <Head>
                <title>Ilia Karavaev - Homepage</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
                <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com"/>


            </Head>
            <S.Main>
                <Navbar/>
                <Memoized3dObject/>
                {children}
            </S.Main>

        </>
    )
}